### ISSUE TITLE
TLE gives NaN propagation result

### ISSUE THREAD

**Issue by JaimeBardaji** [code-lab-org/tatc#29]
CICERO 8 satellite

"1 43737U 18096U   23104.23131873  .00314780  00000+0  18505-2 0  9999",
 "2 43737  97.3248 199.0316 0005801 347.9317  12.1809 15.77351267244832"

Inspection with sgp4 indicates error 2, which is "mean motion has fallen bellow 0". TAT-C should detect and handle this condition.

**Comment by ptgrogan** [comment]
This is an interesting case. The pasted TLE contains some non-breaking spaces (generally display as identical to regular spaces but are a different character which apparently throws a code 2 error in SGP4). This issue should be caught in the TLE validation check.

**Comment by ptgrogan** [comment]
FYI this issue has been raised with the [underlying library ](https://github.com/brandon-rhodes/python-sgp4/issues/116) and will generate a more informative error in future versions.
